benchmark_cfg/ih_t2i.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/dalle.py

Adding DallE-3, renaming old DallE as DallE2.
What it does:
* Call API from OpenAI. 
* Return blank image if violate policy.

Adding DALLE3

---

benchmark_cfg/ih_t2i.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/pixart_alpha.py
src/imagen_hub/infermodels/sdxl.py

#1 Adding SDXL-Turbo and PixArtAlpha

Adding SDXL-Turbo, PixArtAlpha

---

benchmark_cfg/ih_t2i.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/sdxl.py

#1 
Adding Segmind SD (SDXL family). 
https://blog.segmind.com/introducing-segmind-ssd-1b/

adding SSD

---

.gitignore
benchmark_cfg/ih_text-guided.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/pnp.py
src/imagen_hub/pipelines/pnp/pnp.py
src/imagen_hub/pipelines/pnp/pnp_utils.py
src/imagen_hub/pipelines/pnp/preprocess.py

* Adding PNP (support diffusers 0.21+).

Adding PNP (Plug-and-Play)

---

benchmark_cfg/ih_t2i.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/pnp.py
src/imagen_hub/infermodels/sd.py

#1 
* Adding PlayGroundV2
* Adding Docs to PNP

Adding PlaygroundV2

---

src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/sd.py
src/imagen_hub/infermodels/sdxl.py

Add implementation for SDXL-Lightning and StableCascade

---

benchmark_cfg/ih_control-guided.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/freecontrol.py
src/imagen_hub/infermodels/wuerstchen.py
src/imagen_hub/pipelines/freecontrol/__init__.py
src/imagen_hub/pipelines/freecontrol/config/base.yaml
src/imagen_hub/pipelines/freecontrol/config/gradio_info.yaml
src/imagen_hub/pipelines/freecontrol/controlnet_processor.py
src/imagen_hub/pipelines/freecontrol/module/__init__.py
src/imagen_hub/pipelines/freecontrol/module/conv_layer.py
src/imagen_hub/pipelines/freecontrol/module/scheduler.py
src/imagen_hub/pipelines/freecontrol/module/xformer_attention.py
src/imagen_hub/pipelines/freecontrol/pipeline_utils.py
src/imagen_hub/pipelines/freecontrol/pipelines.py
src/imagen_hub/pipelines/freecontrol/sd_pipeline.py
src/imagen_hub/pipelines/freecontrol/utils.py

Add FreeControl Model

---

README.md
benchmark_cfg/ih_t2i.yml
benchmark_cfg/ih_text-guided.yml

Added CosXL Exp

---

src/imagen_hub/infermodels/cosxl.py

Update cosxl path

---

src/imagen_hub/infermodels/pixart_sigma.py

Pix Art Sigma

---

tests/test_t2i.py

added tests for t2i models

---

benchmark_cfg/ih_t2i.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/hunyuan.py

Adding hunyuanDiT

---

benchmark_cfg/ih_t2i.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/sd3.py

Adding SD3

---

benchmark_cfg/ih_text-guided.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/ultraedit.py
src/imagen_hub/pipelines/ultraedit/pipeline_stable_diffusion_3_instructpix2pix.py

#1 
Title
Adding SD3 InstructPix2Pix pipeline

adding ultraedit

---

benchmark_cfg/ih_t2i.yml
src/imagen_hub/__init__.py
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/auraflow.py
src/imagen_hub/infermodels/kolors.py
src/imagen_hub/pipelines/kolors/models/configuration_chatglm.py
src/imagen_hub/pipelines/kolors/models/modeling_chatglm.py
src/imagen_hub/pipelines/kolors/models/tokenization_chatglm.py
src/imagen_hub/pipelines/kolors/pipelines/pipeline_stable_diffusion_xl_chatglm_256.py

Title
AuraFlow will be released once diffusers released official update.

Adding Kolor (and auraflow)

---

benchmarking.py
src/imagen_hub/infermodels/ultraedit.py

updating UltraEdit

---

benchmark_cfg/ih_t2i.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/auraflow.py
src/imagen_hub/infermodels/flux.py

adding AuraFlow and Flux. [Requires torch>=2.2.2]

---

benchmark_cfg/ih_text-guided.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/instructpix2pix.py

Extending InstructPix2Pix family.
#1

Adding AURORA

---

benchmark_cfg/ih_t2i.yml
benchmark_cfg/ih_text-guided.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/cogview.py
src/imagen_hub/infermodels/flowedit.py
src/imagen_hub/pipelines/flowedit/FlowEdit_utils.py

Title
Somehow FlowEdit Flux is not working. But I directly copied from official HF space, so it could be dependencies issue.

Adding CogView, FlowEdit (SD3)

---

src/imagen_hub/utils/html.py
src/imagen_hub/utils/visualizer.py

Adding Button to Hide/View columns in Vis page

---

benchmark_cfg/ih_text-guided.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/gemini.py
src/imagen_hub/utils/image_helper.py

Title
Added Gemini 2.0 Flash for Image editing

Adding Gemini 2.0 Flash Exp for Editing

---

benchmark_cfg/ih_text-guided.yml
src/imagen_hub/infermodels/__init__.py
src/imagen_hub/infermodels/flux_edit.py

Adding FluxEdit: https://github.com/sayakpaul/flux-image-editing/

Add FluxEdit

---

src/imagen_hub/infermodels/flux_edit.py

Fix minor errors in FluxEdit
